### PR TITLE
The improvement has arrived

### PR DESCRIPTION
**Pull request by Happypig375**
>(needs improvement for sure XD)

### CODE REVIEW

**Comment by WhiteBlackGoose** [comment]
I like quotations more. 🐷. Mb you can combine them into qutation + list element?

**Comment by WhiteBlackGoose** [comment]
This is a brand new repo after thiese changes

**Comment by Happypig375** [comment]
Ok
> qutation

> thiese

**Comment by WhiteBlackGoose** [comment]
Yiesъ.

**Pull request merged**
